### Ejemplo válido de registro de usuario
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "nombre": "Miguel A",
  "apellidos": "López Martínez",
  "email": "migue2@example.com",
  "usuario": "miguel_dev",
  "password": "12345678",
  "fecha_nacimiento": "1987-09-23",
  "foto": "https://example.com/foto-perfil.jpg",
  "direccion": "Carrer de la Mar, 45, Sóller"
}

### Ejemplo inválido de registro de usuario
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "nombre": "",
  "apellidos": "López",
  "email": "correo-no-valido",
  "usuario": "usuario_demasiado_largo_que_supera_el_limite_de_caracteres_permitidos_por_el_schema",
  "password": "",
  "fecha_nacimiento": "",
  "foto": "no-es-una-url",
  "direccion": ""
}

### LOGIN CORRECTO
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "miguel@example.com",
  "password": "ClaveSegura123"
}

### LOGIN INCORRECTO
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "usuario@correo.com",
  "password": "123456"
}


## Peticiones de listado de usuarios de admin
## mog 11062026

### LOGIN CORRECTO para obtener token de admin
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "administrador1@revendo.com",
  "password": "123456"
}


### Obtener usuarios (página 1, 20 resultados)
GET http://localhost:3000/api/admin/users?page=1&limit=20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyLCJ1c2VybmFtZSI6ImFkbWluaXN0cmFkb3IxIiwiZW1haWwiOiJhZG1pbmlzdHJhZG9yMUByZXZlbmRvLmNvbSIsInBlcmZpbCI6IkFETUlOIiwiaWF0IjoxNzgxMTg1MDU5fQ.1fA3llrG8TWxMckNxf2QO4xLKVf_RzbUovry6ojBAKQ

### Eliminar usuario 16
DELETE http://localhost:3000/api/admin/users/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyLCJ1c2VybmFtZSI6ImFkbWluaXN0cmFkb3IxIiwiZW1haWwiOiJhZG1pbmlzdHJhZG9yMUByZXZlbmRvLmNvbSIsInBlcmZpbCI6IkFETUlOIiwiaWF0IjoxNzgxMTg1MDU5fQ.1fA3llrG8TWxMckNxf2QO4xLKVf_RzbUovry6ojBAKQ


### Bloquear usuario 17
PUT http://localhost:3000/api/admin/users/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyLCJ1c2VybmFtZSI6ImFkbWluaXN0cmFkb3IxIiwiZW1haWwiOiJhZG1pbmlzdHJhZG9yMUByZXZlbmRvLmNvbSIsInBlcmZpbCI6IkFETUlOIiwiaWF0IjoxNzgxMTg1MDU5fQ.1fA3llrG8TWxMckNxf2QO4xLKVf_RzbUovry6ojBAKQ
Content-Type: application/json

{
  "isBlocked": 1
}


### Buscar usuario por ID
GET http://localhost:3000/api/admin/users/search/id/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyLCJ1c2VybmFtZSI6ImFkbWluaXN0cmFkb3IxIiwiZW1haWwiOiJhZG1pbmlzdHJhZG9yMUByZXZlbmRvLmNvbSIsInBlcmZpbCI6IkFETUlOIiwiaWF0IjoxNzgxMTg1MDU5fQ.1fA3llrG8TWxMckNxf2QO4xLKVf_RzbUovry6ojBAKQ


### Buscar usuario por username
GET http://localhost:3000/api/admin/users/search/username/ivanm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyLCJ1c2VybmFtZSI6ImFkbWluaXN0cmFkb3IxIiwiZW1haWwiOiJhZG1pbmlzdHJhZG9yMUByZXZlbmRvLmNvbSIsInBlcmZpbCI6IkFETUlOIiwiaWF0IjoxNzgxMTg1MDU5fQ.1fA3llrG8TWxMckNxf2QO4xLKVf_RzbUovry6ojBAKQ


### Buscar usuario por email
GET http://localhost:3000/api/admin/users/search/email/administrador1@revendo.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyLCJ1c2VybmFtZSI6ImFkbWluaXN0cmFkb3IxIiwiZW1haWwiOiJhZG1pbmlzdHJhZG9yMUByZXZlbmRvLmNvbSIsInBlcmZpbCI6IkFETUlOIiwiaWF0IjoxNzgxMTg1MDU5fQ.1fA3llrG8TWxMckNxf2QO4xLKVf_RzbUovry6ojBAKQ
