### Ejemplo válido de registro de usuario
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "nombre": "Miguel A",
  "apellidos": "López Martínez",
  "email": "migue2@example.com",
  "usuario": "miguel_dev",
  "password": "12345678",
  "fecha_nacimiento": "1987-09-23",
  "foto": "https://example.com/foto-perfil.jpg",
  "direccion": "Carrer de la Mar, 45, Sóller"
}

### Ejemplo inválido de registro de usuario
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "nombre": "",
  "apellidos": "López",
  "email": "correo-no-valido",
  "usuario": "usuario_demasiado_largo_que_supera_el_limite_de_caracteres_permitidos_por_el_schema",
  "password": "",
  "fecha_nacimiento": "",
  "foto": "no-es-una-url",
  "direccion": ""
}

### LOGIN CORRECTO
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "miguel@example.com",
  "password": "ClaveSegura123"
}

### LOGIN INCORRECTO
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "usuario@correo.com",
  "password": "123456"
}

#################
####ARTÍCULOS####
#################

### Obtener un articulo por su ID
GET http://localhost:3001/api/article/24